export const card = reactive([
  {
    id: 1,
    category: {
      id: 1,
      name: 'Healthy',
    },
    img: '/_nuxt/assets/images/OurDishes/product1.png',
    title: 'Chicken Hell',
    time: '24min',
    rating: 4.8,
    price: 12,
    count: 0,
  },
  {
    id: 2,
    category: {
      id: 2,
      name: 'Trending',
    },
    img: '/_nuxt/assets/images/OurDishes/product2.png',
    title: 'Swe Dish',
    time: '24min',
    rating: 4.9,
    price: 12,
    count: 0,
  },
  {
    id: 3,
    category: {
      id: 3,
      name: 'Healthy',
    },
    img: '/_nuxt/assets/images/OurDishes/product3.png',
    title: 'Chicken Hell',
    time: '24min',
    rating: 4.8,
    price: 12,
    count: 0,
  },
  {
    id: 4,
    category: {
      id: 3,
      name: 'Healthy',
    },
    img: '/_nuxt/assets/images/OurDishes/product4.png',
    title: 'Swe Dish',
    time: '24min',
    rating: 4.8,
    price: 12,
    count: 0,
  },
  {
    id: 5,
    category: {
      id: 3,
      name: 'Healthy',
    },
    img: '/_nuxt/assets/images/OurDishes/product5.png',
    title: 'Chicken Hell',
    time: '24min',
    rating: 4.8,
    price: 12,
    count: 0,
  },
]);
